[package]
name = "scraprs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.152"
thirtyfour = "0.31.0"
tokio = { version = "1.25.0", features = ["full"] }
toml = "0.7.2"
